[package]
name = "mini-apm-cli"
edition.workspace = true
version.workspace = true
publish = false

[dependencies]
mini-apm = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
tracing-subscriber = { workspace = true }
anyhow = { workspace = true }